# Cleaning Data
In this file, I will be making all of my different data frames follow the same format to one another in order to apply different feature importance methods.

In [1]:
import pandas as pd

In [2]:
# Abbreviations for all the states
value_mapping = {
    'United States': 'US',
    'Alabama': 'AL',
    'Alaska': 'AK', 
    'Arizona': 'AZ', 
    'Arkansas': 'AR', 
    'California': 'CA',
    'Colorado': 'CO', 
    'Connecticut': 'CT', 
    'Delaware': 'DE', 
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI', 
    'Idaho': 'ID', 
    'Illinois': 'IL',
    'Indiana': 'IN', 
    'Iowa': 'IA', 
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI', 
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

In [3]:
# Function that cleanes the CSV fle
def clean_csv(filepath, valuemapping, format='Percent', column_name=None):
    df = pd.read_excel(filepath)
    df['Location'] = df['Location'].replace(valuemapping)
    if yearmap:
        df['TimeFrame'] = df['TimeFrame'].replace(year_map)
    df['LocYear'] = df['Location'].astype(str) + df['TimeFrame'].astype(str)
    result = df[df['DataFormat'] == format].pivot_table(
        index='LocYear', 
        columns=column_name, 
        values='Data', 
        aggfunc='sum'
    )
    result.columns.name = None
    result = result.reset_index()
    return result

## Target Cleaning
The data comes from: [State-Level Estimates of Household Firearm Ownership](https://www.rand.org/pubs/tools/TL354.html).  
Estimates of household firearm ownership rates are found in the field labeled "HFR" which I will most likely be using for my target.   
***
The variables are as follows:  

| Varname | Description |
| --- | --- |
| FIP | State FIP vale |
| Year | Year |
| STATE | State name |
| HFR | Factor scores for household firearm ownership latent factor |
| HFR_se | Standard errors of factor scores for household firearm ownership latent factor |
| universl | State has universal background checks law (1=yes; 0=no) |
| permit | State has permit to purchase law (1=yes; 0=no) |
| Fem_FS_S | Female Firearm Suicide/Total Male Suicide *100 |
| Male_FS_S | Male Firearm Suicide/Total Male Suicide *100 |
| BRFSS | BRFSS state-level survey estimate |
| GALLUP | Gallup state-level survey estimate |
| GSS | General Social Survey state-level survey estimate |
| PEW | Pew state-level survey estimate |
| HuntLic | Square root of Hunting Licenses/Population |
| GunsAmmo | Within-year standardization of the square root of Guns and Ammo Subscriptions/Population |
| BackChk | Within-year standardization of Background Checks (without checks for permits)/Population |
| PewQChng | Indicator for Pew firearm ownership question wording change |
| BS1 | Blended linear spline 1 represents roughly 1980–1992 |
| BS2 | Blended linear spline 2 represents roughly 1993–2004 |
| BS3 | Blended linear spline 3 represents roughly 2005–2016 |

In [4]:
df = pd.read_csv("data/gunownerdata.csv")
df['STATE'] = df['STATE'].replace(value_mapping) # Changing state names to abbreviations
df['LocYear'] = df['STATE'].astype(str) + df['Year'].astype(str) # Combining state names and years into new index column called LocYear

In [5]:
df

,FIP,Year,STATE,HFR,HFR_se,universl,permit,Fem_FS_S,Male_FS_S,BRFSS,...,GSS,PEW,HuntLic,GunsAmmo,BackChk,PewQChng,BS1,BS2,BS3,LocYear
0,1,1980,AL,0.608,0.031,0,0,0.824324,0.833795,-9.0,...,0.583632,-9.000000,0.291102,-0.509164,-9.000000,0,0.0,0.0,0.0,AL1980
1,1,1981,AL,0.597,0.047,0,0,0.692308,0.831126,-9.0,...,-9.000000,-9.000000,0.294962,-0.618954,-9.000000,0,1.0,0.0,0.0,AL1981
2,1,1982,AL,0.661,0.036,0,0,0.771739,0.821429,-9.0,...,0.655196,-9.000000,0.290545,-0.526692,-9.000000,0,2.0,0.0,0.0,AL1982
3,1,1983,AL,0.586,0.038,0,0,0.688172,0.819277,-9.0,...,-9.000000,-9.000000,0.284983,-0.713227,-9.000000,0,3.0,0.0,0.0,AL1983
4,1,1984,AL,0.624,0.036,0,0,0.710000,0.775956,-9.0,...,0.626933,-9.000000,0.281622,-0.733305,-9.000000,0,4.0,0.0,0.0,AL1984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,56,2012,WY,0.597,0.029,0,0,0.375000,0.647482,-9.0,...,-9.000000,0.622224,0.545627,2.973924,1.562481,0,12.0,12.0,8.0,WY2012
1846,56,2013,WY,0.613,0.032,0,0,0.529412,0.714286,-9.0,...,-9.000000,0.685266,0.542697,3.066252,1.638737,1,12.0,12.0,9.0,WY2013
1847,56,2014,WY,0.608,0.044,0,0,0.583333,0.666667,-9.0,...,-9.000000,-9.000000,0.538761,3.092854,1.603822,1,12.0,12.0,10.0,WY2014
1848,56,2015,WY,0.549,0.032,0,0,0.393939,0.661290,-9.0,...,-9.000000,0.611531,0.544356,2.910414,1.348323,1,12.0,12.0,11.0,WY2015
1849,56,2016,WY,0.607,0.032,0,0,0.375000,0.669643,-9.0,...,-9.000000,0.725993,0.538439,2.899840,1.265807,1,12.0,12.0,12.0,WY2016

In [6]:
df = df[df['Year'] >= 2010] # Filtering the data frame to only have data from 2010-2016 since the other features only have data from
                            # this range
df = df.drop(columns=['STATE', 'Year']) # Getting rid of the original state and year columns
df = df.set_index('LocYear')
df.head()

,FIP,HFR,HFR_se,universl,permit,Fem_FS_S,Male_FS_S,BRFSS,GALLUP,GSS,PEW,HuntLic,GunsAmmo,BackChk,PewQChng,BS1,BS2,BS3
LocYear,,,,,,,,,,,,,,,,,,
AL2010,1,0.456,0.028,0,0,0.546099,0.700743,-9.0,-9.000000,0.391567,0.486040,0.225767,-0.250093,1.057550,0,12.0,12.0,6.0
AL2011,1,0.513,0.032,0,0,0.653226,0.700000,-9.0,-9.000000,-9.000000,0.536971,0.349485,-0.260119,0.975045,0,12.0,12.0,7.0
AL2012,1,0.543,0.026,0,0,0.623188,0.706485,-9.0,0.631616,0.496401,0.558550,0.344020,-0.215208,1.066323,0,12.0,12.0,8.0
AL2013,1,0.516,0.032,0,0,0.562092,0.735915,-9.0,-9.000000,-9.000000,0.598503,0.344332,-0.172469,1.202040,1,12.0,12.0,9.0
AL2014,1,0.510,0.035,0,0,0.595890,0.688928,-9.0,-9.000000,0.467335,-9.000000,0.340475,-0.196054,1.242362,1,12.0,12.0,10.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 350 entries, AL2010 to WY2016
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   FIP        350 non-null    int64
 1   HFR        350 non-null    float64
 2   HFR_se     350 non-null    float64
 3   universl   350 non-null    int64
 4   permit     350 non-null    int64
 5   Fem_FS_S   350 non-null    float64
 6   Male_FS_S  350 non-null    float64
 7   BRFSS      350 non-null    float64
 8   GALLUP     350 non-null    float64
 9   GSS        350 non-null    float64
 10  PEW        350 non-null    float64
 11  HuntLic    350 non-null    float64
 12  GunsAmmo   350 non-null    float64
 13  BackChk    350 non-null    float64
 14  PewQChng   350 non-null    int64
 15  BS1        350 non-null    float64
 16  BS2        350 non-null    float64
 17  BS3        350 non-null    float64
dtypes: float64(14), int64(4)
memory usage: 54.0 KB

## BEA Data
All of the following data comes from the [BEA](https://apps.bea.gov/itable/?ReqID=70&step=1&_gl=1*1iohkmg*_ga*MTUyNjY2ODY2My4xNzgwNjA4MDY1*_ga_J4698JNNFT*czE3ODA2MDgwNjQkbzEkZzEkdDE3ODA2MDg4ODMkajYwJGwwJGgw#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI2MDAiXSxbIk1ham9yX0FyZWEiLCIwIl0sWyJTdGF0ZSIsWyIwIl1dLFsiQXJlYSIsWyJYWCJdXSxbIlN0YXRpc3RpYyIsWyI1Il1dLFsiVW5pdF9vZl9tZWFzdXJlIiwiTGV2ZWxzIl0sWyJZZWFyIixbIi0xIl1dLFsiWWVhckJlZ2luIiwiLTEiXSxbIlllYXJfRW5kIiwiLTEiXV19) website.  

U.S. Bureau of Economic Analysis, "[SASUMMARY State annual summary statistics: personal income, GDP, consumer spending, price indexes, and employment](https://apps.bea.gov/itable/?ReqID=70&step=1&_gl=1*1iohkmg*_ga*MTUyNjY2ODY2My4xNzgwNjA4MDY1*_ga_J4698JNNFT*czE3ODA2MDgwNjQkbzEkZzEkdDE3ODA2MDg4ODMkajYwJGwwJGgw#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI2MDAiXSxbIk1ham9yX0FyZWEiLCIwIl0sWyJTdGF0ZSIsWyIwIl1dLFsiQXJlYSIsWyJYWCJdXSxbIlN0YXRpc3RpYyIsWyI1Il1dLFsiVW5pdF9vZl9tZWFzdXJlIiwiTGV2ZWxzIl0sWyJZZWFyIixbIi0xIl1dLFsiWWVhckJlZ2luIiwiLTEiXSxbIlllYXJfRW5kIiwiLTEiXV19)" (accessed Thursday, June 4, 2026).

### Personal Income
- Personal income consists of the income that persons receive in return for their provision of labor, land, and capital used in current production as well as other income, such as personal current transfer receipts
- In the state and local personal income accounts the personal income of an area represents the income received by or on behalf of the persons residing in that area
- It is calculated as the sum of wages and salaries, supplements to wages and salaries, proprietors' income with inventory valuation (IVA) and capital consumption adjustments (CCAdj), rental income of persons with capital consumption adjustment (CCAdj), personal dividend income, personal interest income, and personal current transfer receipts, less contributions for government social insurance plus the adjustment for residence
- The values are in millions of US dollars

In [8]:
money_df = pd.read_excel("data/Table.xlsx")

In [9]:
money_df.head()

,GeoFIPS,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,0,United States,7584003.0,7978449.0,8620234.0,8990104.0,9146700.0,9474684.0,10008929.0,10540800.0,...,15884741.0,16658962.0,17514402.0,18349584.0,19613059.0,21484168.0,22144814.0,23577208.0,24897613.0,26109831.2
1,1000,Alabama,99772.9,103204.1,108002.9,111894.1,115007.7,120241.0,128606.3,136087.5,...,190871.8,197963.8,205674.2,215151.8,230878.4,255682.3,262425.8,279484.6,295590.5,309906.4
2,2000,Alaska,18155.9,18706.6,20092.2,21287.1,22331.5,23372.1,24429.2,26019.6,...,41285.5,41919.4,43522.7,44459.7,45375.8,48327.1,50793.7,53322.0,56423.1,59110.5
3,4000,Arizona,117835.0,124922.3,135573.8,142097.8,147455.2,156408.8,170443.0,187724.9,...,279696.7,297261.5,315459.0,337257.2,374282.4,415893.1,435718.7,471040.2,498903.6,520574.1
4,5000,Arkansas,55686.3,57922.1,60886.2,64168.6,65698.8,69656.4,74308.7,77990.4,...,119758.8,123825.4,128970.8,131394.8,142072.2,161493.9,163688.6,173568.3,183201.8,192345.6

In [10]:
# putting the column in the correct format
personal_inc = money_df.melt(
    id_vars=['GeoFIPS', 'GeoName'],   # columns to keep
    var_name='Year',                  # name for the new year column
    value_name='Personal_Income'      # labeling personal income
)

In [11]:
personal_inc.head()

   GeoFIPS        GeoName  Year  Personal_Income
0        0  United States  1998        7584003.0
1     1000        Alabama  1998          99772.9
2     2000         Alaska  1998          18155.9
3     4000        Arizona  1998         117835.0
4     5000       Arkansas  1998          55686.3

In [12]:
personal_inc['GeoName'] = personal_inc['GeoName'].replace(value_mapping) # Changing state names to abbreviations
personal_inc['LocYear'] = personal_inc['GeoName'].astype(str) + personal_inc['Year'].astype(str) # Combining state names and years into new index column called LocYear
personal_inc = personal_inc.drop(columns=["GeoName", "Year"]) # dropping unneeded columns

In [13]:
personal_inc.head()

   GeoFIPS  Personal_Income LocYear
0        0        7584003.0  US1998
1     1000          99772.9  AL1998
2     2000          18155.9  AK1998
3     4000         117835.0  AZ1998
4     5000          55686.3  AR1998

In [14]:
personal_inc.info()

<class 'pandas.DataFrame'>
RangeIndex: 1456 entries, 0 to 1455
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GeoFIPS          1456 non-null   int64
 1   Personal_Income  1456 non-null   float64
 2   LocYear          1456 non-null   str
dtypes: float64(1), int64(1), str(1)
memory usage: 42.8 KB

### Total Employment
- In terms of number of jobs
- Employment- A count of jobs, both full-time and part-time. It includes wage and salary jobs, sole proprietorships, and individual general partners, but not unpaid family workers nor volunteers

In [15]:
job_df = pd.read_excel("data/employment.xlsx")

In [16]:
job_df.head()

,GeoFIPS,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,0,United States,158481200,161531300,165370800,165522200,165095100,165921500,168839700,172338400,...,193425900,196394100,200292200,201622200,195278600,202705100,210466200,216347200,218181200,(NA)
1,1000,Alabama,2361892,2378217,2392225,2376053,2364829,2371429,2425650,2486829,...,2619761,2649222,2692424,2712014,2670980,2769117,2857149,2931413,2969241,(NA)
2,2000,Alaska,382166,381307,389734,394565,402192,405625,413869,421422,...,457142,455550,454776,454794,430889,443016,454025,467104,474188,(NA)
3,4000,Arizona,2616288,2695892,2801510,2829002,2847070,2917095,3041449,3219799,...,3644791,3740747,3854741,3929587,3919887,4085773,4250495,4404247,4457506,(NA)
4,5000,Arkansas,1445536,1460374,1482449,1482587,1478920,1482026,1505086,1537671,...,1629734,1639903,1658212,1663305,1639041,1684580,1744586,1789021,1805358,(NA)

In [17]:
employment = job_df.melt(
    id_vars=['GeoFIPS', 'GeoName'],   # columns to keep
    var_name='Year',                  # name for the new year column
    value_name='Total_employment'      # labeling personal income
)

In [18]:
employment.head()

   GeoFIPS        GeoName  Year Total_employment
0        0  United States  1998        158481200
1     1000        Alabama  1998          2361892
2     2000         Alaska  1998           382166
3     4000        Arizona  1998          2616288
4     5000       Arkansas  1998          1445536

In [19]:
employment['GeoName'] = employment['GeoName'].replace(value_mapping) # Changing state names to abbreviations
employment['LocYear'] = employment['GeoName'].astype(str) + employment['Year'].astype(str) # Combining state names and years into new index column called LocYear
employment = employment.drop(columns=["GeoName", "Year"]) # dropping unneeded columns

In [20]:
employment.head()

   GeoFIPS Total_employment LocYear
0        0        158481200  US1998
1     1000          2361892  AL1998
2     2000           382166  AK1998
3     4000          2616288  AZ1998
4     5000          1445536  AR1998

In [21]:
# making a function to speed up the process
def bea_transform(df, value_name, value_mapping=value_mapping):
    df = df.melt(
        id_vars=['GeoFIPS', 'GeoName'],   # columns to keep
        var_name='Year',                  # name for the new year column
        value_name=value_name   
    )
    df['GeoName'] = df['GeoName'].replace(value_mapping) # Changing state names to abbreviations
    df['LocYear'] = df['GeoName'].astype(str) + df['Year'].astype(str) # Combining state names and years into new index column called LocYear
    df = df.drop(columns=["GeoName", "Year"]) # dropping unneeded columns
    return df

### Disposable Personal Income
- In millions of current dollars
- The income available to persons for spending or saving. It is equal to personal income less personal current taxes

In [22]:
disp_pers_inc = pd.read_excel("data/disppersonalinc.xlsx")

In [23]:
disp_pers_inc = bea_transform(disp_pers_inc, "Disposable_Personal_Income")

In [24]:
disp_pers_inc.head()

   GeoFIPS  Disposable_Personal_Income LocYear
0        0                   6552573.0  US1998
1     1000                     88548.4  AL1998
2     2000                     16187.6  AK1998
3     4000                    103265.8  AZ1998
4     5000                     49470.1  AR1998

### Personal Consumption Expenditures 
- Personal consumption expenditures by state- A measure of spending on goods and services purchased by, and on behalf of, households based on households' state of residence in the fifty states and the District of Columbia
- In millions of current dollars

In [25]:
pce = pd.read_excel("data/pers_consum_exp.xlsx")

In [26]:
pce = bea_transform(pce, "Personal_Consumption_Expenditures")

In [27]:
pce.head()

   GeoFIPS Personal_Consumption_Expenditures LocYear
0        0                         5877248.2  US1998
1     1000                           80320.5  AL1998
2     2000                           14946.5  AK1998
3     4000                          103774.8  AZ1998
4     5000                           44283.3  AR1998

### Merging BEA Data
- Everything will be merged on LocYear since this is my index column

In [28]:
df1 = pd.merge(personal_inc, employment, on=["GeoFIPS", "LocYear"])
df1.head()

   GeoFIPS  Personal_Income LocYear Total_employment
0        0        7584003.0  US1998        158481200
1     1000          99772.9  AL1998          2361892
2     2000          18155.9  AK1998           382166
3     4000         117835.0  AZ1998          2616288
4     5000          55686.3  AR1998          1445536

In [29]:
df2 = pd.merge(df1, disp_pers_inc, on=["GeoFIPS", "LocYear"])
df2.head()

,GeoFIPS,Personal_Income,LocYear,Total_employment,Disposable_Personal_Income
0,0,7584003.0,US1998,158481200,6552573.0
1,1000,99772.9,AL1998,2361892,88548.4
2,2000,18155.9,AK1998,382166,16187.6
3,4000,117835.0,AZ1998,2616288,103265.8
4,5000,55686.3,AR1998,1445536,49470.1

In [30]:
bea_df = pd.merge(df2, pce, on=["GeoFIPS", "LocYear"])
bea_df = bea_df.set_index('LocYear')
bea_df.head()

,GeoFIPS,Personal_Income,Total_employment,Disposable_Personal_Income,Personal_Consumption_Expenditures
LocYear,,,,,
US1998,0,7584003.0,158481200,6552573.0,5877248.2
AL1998,1000,99772.9,2361892,88548.4,80320.5
AK1998,2000,18155.9,382166,16187.6,14946.5
AZ1998,4000,117835.0,2616288,103265.8,103774.8
AR1998,5000,55686.3,1445536,49470.1,44283.3

## Census Data
- All of the data in the following section was obtained from the [US Census](https://www.census.gov/)

### PUBLIC ASSISTANCE INCOME OR FOOD STAMPS/SNAP IN THE PAST 12 MONTHS FOR HOUSEHOLDS
Survey/Program: American Community Survey  
Universe: Households  
Year: 2010  
Estimates: 1-Year  
Table ID: B19058  
***
*All of the data from the Census is separate per year, so I will have to individually download all the year files*
- In the data folder, the data for each of these variables is labeled, and then the individual data tables are labeled by year

### 2010
- In this year, I just figured out the pipeline

In [31]:
df2010 = pd.read_csv("data/income_food/2010.csv")

In [32]:
rename = {
    "GEO_ID" : "Geography",
    "B19058_001E" : "Total",
    "B19058_001M" : "ME_Total",
    "B19058_002E" : "CashPublicAssistanceORFoodStamps/SNAP",
    "B19058_002M" : "ME_CashPublicAssistanceORFoodStamps/SNAP",
    "B19058_003E" : "NoCashPublicAssistanceORFoodStamps/SNAP",
    "B19058_003M" : "ME_NoCashPublicAssistanceORFoodStamps/SNAP"
}

In [33]:
df2010 = df2010.rename(columns=rename)
df2010 = df2010.drop(0)
df2010.head()

,Geography,NAME,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,Unnamed: 8
1,0100000US,United States,114567419,163249,14535659,58768,100031760,152697,NaN
2,0400000US01,Alabama,1815152,10938,267955,9889,1547197,13133,NaN
3,0400000US02,Alaska,254610,2804,33844,2384,220766,3411,NaN
4,0400000US04,Arizona,2334050,12895,326662,10123,2007388,12431,NaN
5,0400000US05,Arkansas,1114902,8104,159070,6193,955832,7912,NaN

In [34]:
df2010['NAME'] = df2010['NAME'].replace(value_mapping) # Changing state names to abbreviations
df2010['LocYear'] = df2010['NAME'].astype(str) + '2010' # Combining state names and years into new index column called LocYear
df2010 = df2010.drop(columns=["NAME", "Unnamed: 8"]) # dropping unneeded columns

In [35]:
df2010.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,114567419,163249,14535659,58768,100031760,152697,US2010
2,0400000US01,1815152,10938,267955,9889,1547197,13133,AL2010
3,0400000US02,254610,2804,33844,2384,220766,3411,AK2010
4,0400000US04,2334050,12895,326662,10123,2007388,12431,AZ2010
5,0400000US05,1114902,8104,159070,6193,955832,7912,AR2010

In [36]:
# function for making the process quicker for the other dataframes
def cleaning_public_assistance(df, year, rename=rename, value_mapping=value_mapping):
    df = df.rename(columns=rename)
    df = df.drop(0)
    df['NAME'] = df['NAME'].replace(value_mapping)
    df['LocYear'] = df['NAME'].astype(str) + year
    df = df.drop(columns=["NAME", "Unnamed: 8"])
    return df

#### 2011

In [37]:
df2011 = pd.read_csv("data/income_food/2011.csv")
df2011.head()

,GEO_ID,NAME,B19058_001E,B19058_001M,B19058_002E,B19058_002M,B19058_003E,B19058_003M,Unnamed: 8
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!With cash public assistance o...,Margin of Error!!Total!!With cash public assis...,Estimate!!Total!!No cash public assistance or ...,Margin of Error!!Total!!No cash public assista...,NaN
1,0100000US,United States,114991725,179541,15782796,59429,99208929,163750,NaN
2,0400000US01,Alabama,1844546,11416,322370,8606,1522176,10634,NaN
3,0400000US02,Alaska,257330,3380,32661,2699,224669,3240,NaN
4,0400000US04,Arizona,2356055,12130,344392,10288,2011663,13828,NaN

In [38]:
df2011 = cleaning_public_assistance(df2011, '2011')
df2011.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,114991725,179541,15782796,59429,99208929,163750,US2011
2,0400000US01,1844546,11416,322370,8606,1522176,10634,AL2011
3,0400000US02,257330,3380,32661,2699,224669,3240,AK2011
4,0400000US04,2356055,12130,344392,10288,2011663,13828,AZ2011
5,0400000US05,1127621,7837,180949,7741,946672,8673,AR2011

#### 2012

In [39]:
df2012 = pd.read_csv("data/income_food/2012.csv")
df2012.head()

,GEO_ID,NAME,B19058_001E,B19058_001M,B19058_002E,B19058_002M,B19058_003E,B19058_003M,Unnamed: 8
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!With cash public assistance o...,Margin of Error!!Total!!With cash public assis...,Estimate!!Total!!No cash public assistance or ...,Margin of Error!!Total!!No cash public assista...,NaN
1,0100000US,United States,115969540,150555,16610889,61312,99358651,148324,NaN
2,0400000US01,Alabama,1845169,11483,317821,7863,1527348,11730,NaN
3,0400000US02,Alaska,251651,2883,35264,2537,216387,3271,NaN
4,0400000US04,Arizona,2392168,11611,359500,8197,2032668,12889,NaN

In [40]:
df2012 = cleaning_public_assistance(df2012, '2012')
df2012.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,115969540,150555,16610889,61312,99358651,148324,US2012
2,0400000US01,1845169,11483,317821,7863,1527348,11730,AL2012
3,0400000US02,251651,2883,35264,2537,216387,3271,AK2012
4,0400000US04,2392168,11611,359500,8197,2032668,12889,AZ2012
5,0400000US05,1143859,7351,181527,5312,962332,8261,AR2012

#### 2013

In [41]:
df2013 = pd.read_csv("data/income_food/2013.csv")
df2013.head()

,GEO_ID,NAME,B19058_001E,B19058_001M,B19058_002E,B19058_002M,B19058_003E,B19058_003M,Unnamed: 8
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!With cash public assistance o...,Margin of Error!!Total!!With cash public assis...,Estimate!!Total!!No cash public assistance or ...,Margin of Error!!Total!!No cash public assista...,NaN
1,0100000US,United States,116291033,141632,16505893,54782,99785140,145605,NaN
2,0400000US01,Alabama,1822439,11200,292257,7689,1530182,12051,NaN
3,0400000US02,Alaska,246015,2720,32156,2414,213859,3413,NaN
4,0400000US04,Arizona,2400809,11557,339500,8034,2061309,12174,NaN

In [42]:
df2013 = cleaning_public_assistance(df2013, '2013')
df2013.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,116291033,141632,16505893,54782,99785140,145605,US2013
2,0400000US01,1822439,11200,292257,7689,1530182,12051,AL2013
3,0400000US02,246015,2720,32156,2414,213859,3413,AK2013
4,0400000US04,2400809,11557,339500,8034,2061309,12174,AZ2013
5,0400000US05,1125899,6925,177856,6289,948043,8172,AR2013

#### 2014

In [43]:
df2014 = pd.read_csv("data/income_food/2014.csv")
df2014.head()

,GEO_ID,NAME,B19058_001E,B19058_001M,B19058_002E,B19058_002M,B19058_003E,B19058_003M,Unnamed: 8
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!With cash public assistance o...,Margin of Error!!Total!!With cash public assis...,Estimate!!Total!!No cash public assistance or ...,Margin of Error!!Total!!No cash public assista...,NaN
1,0100000US,United States,117259427,146938,16262389,60894,100997038,149660,NaN
2,0400000US01,Alabama,1841217,10615,299007,7523,1542210,11388,NaN
3,0400000US02,Alaska,249659,2978,30970,2203,218689,2966,NaN
4,0400000US04,Arizona,2428743,11353,335176,8376,2093567,11886,NaN

In [44]:
df2014 = cleaning_public_assistance(df2014, '2014')
df2014.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,117259427,146938,16262389,60894,100997038,149660,US2014
2,0400000US01,1841217,10615,299007,7523,1542210,11388,AL2014
3,0400000US02,249659,2978,30970,2203,218689,2966,AK2014
4,0400000US04,2428743,11353,335176,8376,2093567,11886,AZ2014
5,0400000US05,1131288,8373,167346,6225,963942,8721,AR2014

#### 2015

In [45]:
df2015 = pd.read_csv("data/income_food/2015.csv")
df2015.head()

,GEO_ID,NAME,B19058_001E,B19058_001M,B19058_002E,B19058_002M,B19058_003E,B19058_003M,Unnamed: 8
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!With cash public assistance o...,Margin of Error!!Total!!With cash public assis...,Estimate!!Total!!No cash public assistance or ...,Margin of Error!!Total!!No cash public assista...,NaN
1,0100000US,United States,118208250,155130,15938696,56568,102269554,164770,NaN
2,0400000US01,Alabama,1846390,11341,292070,9100,1554320,12079,NaN
3,0400000US02,Alaska,250185,2685,33620,2352,216565,3442,NaN
4,0400000US04,Arizona,2463008,12455,336953,7518,2126055,12859,NaN

In [46]:
df2015 = cleaning_public_assistance(df2015, '2015')
df2015.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,118208250,155130,15938696,56568,102269554,164770,US2015
2,0400000US01,1846390,11341,292070,9100,1554320,12079,AL2015
3,0400000US02,250185,2685,33620,2352,216565,3442,AK2015
4,0400000US04,2463008,12455,336953,7518,2126055,12859,AZ2015
5,0400000US05,1144663,8300,161934,6335,982729,8233,AR2015

#### 2016

In [47]:
df2016 = pd.read_csv("data/income_food/2016.csv")
df2016.head()

,GEO_ID,NAME,B19058_001E,B19058_001M,B19058_002E,B19058_002M,B19058_003E,B19058_003M,Unnamed: 8
0,Geography,Geographic Area Name,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!With cash public assistance o...,Margin of Error!!Total!!With cash public assis...,Estimate!!Total!!No cash public assistance or ...,Margin of Error!!Total!!No cash public assista...,NaN
1,0100000US,United States,118860065,154606,15516032,61677,103344033,164424,NaN
2,0400000US01,Alabama,1852518,12189,276758,8035,1575760,12566,NaN
3,0400000US02,Alaska,248468,2841,32677,2924,215791,3703,NaN
4,0400000US04,Arizona,2519052,11479,325440,7626,2193612,12546,NaN

In [48]:
df2016 = cleaning_public_assistance(df2016, '2016')
df2016.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
1,0100000US,118860065,154606,15516032,61677,103344033,164424,US2016
2,0400000US01,1852518,12189,276758,8035,1575760,12566,AL2016
3,0400000US02,248468,2841,32677,2924,215791,3703,AK2016
4,0400000US04,2519052,11479,325440,7626,2193612,12546,AZ2016
5,0400000US05,1142718,7341,147890,5896,994828,8238,AR2016

### Combining all Public Assistance Income OR Food Stamps/SNAP Data from 2010-2016

In [58]:
# 2010-2011
df1 = pd.concat([df2010, df2011], ignore_index=True)
df1.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
0,0100000US,114567419,163249,14535659,58768,100031760,152697,US2010
1,0400000US01,1815152,10938,267955,9889,1547197,13133,AL2010
2,0400000US02,254610,2804,33844,2384,220766,3411,AK2010
3,0400000US04,2334050,12895,326662,10123,2007388,12431,AZ2010
4,0400000US05,1114902,8104,159070,6193,955832,7912,AR2010

In [59]:
# 2012-2013
df2 = pd.concat([df2012, df2013], ignore_index=True)
df2.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
0,0100000US,115969540,150555,16610889,61312,99358651,148324,US2012
1,0400000US01,1845169,11483,317821,7863,1527348,11730,AL2012
2,0400000US02,251651,2883,35264,2537,216387,3271,AK2012
3,0400000US04,2392168,11611,359500,8197,2032668,12889,AZ2012
4,0400000US05,1143859,7351,181527,5312,962332,8261,AR2012

In [60]:
# 2014-2015
df3 = pd.concat([df2014, df2015], ignore_index=True)
df3.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
0,0100000US,117259427,146938,16262389,60894,100997038,149660,US2014
1,0400000US01,1841217,10615,299007,7523,1542210,11388,AL2014
2,0400000US02,249659,2978,30970,2203,218689,2966,AK2014
3,0400000US04,2428743,11353,335176,8376,2093567,11886,AZ2014
4,0400000US05,1131288,8373,167346,6225,963942,8721,AR2014

In [61]:
# 2010-2013
df4 = pd.concat([df1, df2], ignore_index=True)
df4.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
0,0100000US,114567419,163249,14535659,58768,100031760,152697,US2010
1,0400000US01,1815152,10938,267955,9889,1547197,13133,AL2010
2,0400000US02,254610,2804,33844,2384,220766,3411,AK2010
3,0400000US04,2334050,12895,326662,10123,2007388,12431,AZ2010
4,0400000US05,1114902,8104,159070,6193,955832,7912,AR2010

In [62]:
# 2010-2015
df5 = pd.concat([df4, df3], ignore_index=True)
df5.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
0,0100000US,114567419,163249,14535659,58768,100031760,152697,US2010
1,0400000US01,1815152,10938,267955,9889,1547197,13133,AL2010
2,0400000US02,254610,2804,33844,2384,220766,3411,AK2010
3,0400000US04,2334050,12895,326662,10123,2007388,12431,AZ2010
4,0400000US05,1114902,8104,159070,6193,955832,7912,AR2010

In [63]:
# 2010-2016
public_assist_df = pd.concat([df5, df2016], ignore_index=True)
public_assist_df.head()

,Geography,Total,ME_Total,CashPublicAssistanceORFoodStamps/SNAP,ME_CashPublicAssistanceORFoodStamps/SNAP,NoCashPublicAssistanceORFoodStamps/SNAP,ME_NoCashPublicAssistanceORFoodStamps/SNAP,LocYear
0,0100000US,114567419,163249,14535659,58768,100031760,152697,US2010
1,0400000US01,1815152,10938,267955,9889,1547197,13133,AL2010
2,0400000US02,254610,2804,33844,2384,220766,3411,AK2010
3,0400000US04,2334050,12895,326662,10123,2007388,12431,AZ2010
4,0400000US05,1114902,8104,159070,6193,955832,7912,AR2010

In [64]:
public_assist_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 8 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Geography                                   371 non-null    str
 1   Total                                       371 non-null    str
 2   ME_Total                                    371 non-null    str
 3   CashPublicAssistanceORFoodStamps/SNAP       371 non-null    str
 4   ME_CashPublicAssistanceORFoodStamps/SNAP    371 non-null    str
 5   NoCashPublicAssistanceORFoodStamps/SNAP     371 non-null    str
 6   ME_NoCashPublicAssistanceORFoodStamps/SNAP  371 non-null    str
 7   LocYear                                     371 non-null    str
dtypes: str(8)
memory usage: 41.5 KB