# Is Political Ideology a Better Indicator of Gun Ownership?
- As the title says, this is what I will be exploring in the file
- All the data in this file is found from [State Partisan Composition](https://www.ncsl.org/about-state-legislatures/state-partisan-composition)

In [1]:
import pandas as pd

In [2]:
value_mapping = {
    'United States': 'US',
    'Alabama': 'AL',
    'Alaska': 'AK', 
    'Arizona': 'AZ', 
    'Arkansas': 'AR', 
    'California': 'CA',
    'Colorado': 'CO', 
    'Connecticut': 'CT', 
    'Delaware': 'DE', 
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI', 
    'Idaho': 'ID', 
    'Illinois': 'IL',
    'Indiana': 'IN', 
    'Iowa': 'IA', 
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI', 
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

### 2010
- The data from this table was taken from [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)
- Instead of keeping all of the columns, I wanted to just look at the leaning of each state, so I calculated the leaning of the senate, leaning of the house, and then just averaged the two

In [3]:
pol2010 = pd.read_csv("../data/political/2010.csv")

In [4]:
pol2010.head()

pol2010["House Dem Rate"] = pol2010["House Dem"] / pol2010["Total House"]

In [5]:
pol2010["House Rep Rate"] = pol2010["House Rep"] / pol2010["Total House"]
pol2010["Senate Dem Rate"] = pol2010["Senate Dem"] / pol2010["Total Senate"]
pol2010["Senate Rep Rate"] = pol2010["Senate Rep"] / pol2010["Total Senate"]

In [6]:
pol2010.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control,House Dem Rate,House Rep Rate,Senate Dem Rate,Senate Rep Rate
0,Alabama,105.0,60.0,45.0,NaN,NaN,35,21.0,14.0,NaN,NaN,D,R,S,0.571429,0.428571,0.600000,0.400000
1,Alaska,40.0,18.0,22.0,NaN,NaN,20,10.0,10.0,NaN,NaN,S,R,S,0.450000,0.550000,0.500000,0.500000
2,Arizona,60.0,25.0,35.0,NaN,NaN,30,12.0,18.0,NaN,NaN,R,R,R,0.416667,0.583333,0.400000,0.600000
3,Arkansas,100.0,71.0,28.0,1.0,NaN,35,27.0,8.0,NaN,NaN,D,D,D,0.710000,0.280000,0.771429,0.228571
4,California,80.0,49.0,29.0,1.0,1.0,40,25.0,14.0,NaN,1.0,D,R,S,0.612500,0.362500,0.625000,0.350000

In [7]:
pol2010["House Leaning"] = pol2010["House Dem Rate"] - pol2010["House Rep Rate"]
pol2010["Senate Leaning"] = pol2010["Senate Dem Rate"] - pol2010["Senate Rep Rate"]

In [8]:
pol2010.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control,House Dem Rate,House Rep Rate,Senate Dem Rate,Senate Rep Rate,House Leaning,Senate Leaning
0,Alabama,105.0,60.0,45.0,NaN,NaN,35,21.0,14.0,NaN,NaN,D,R,S,0.571429,0.428571,0.600000,0.400000,0.142857,0.200000
1,Alaska,40.0,18.0,22.0,NaN,NaN,20,10.0,10.0,NaN,NaN,S,R,S,0.450000,0.550000,0.500000,0.500000,-0.100000,0.000000
2,Arizona,60.0,25.0,35.0,NaN,NaN,30,12.0,18.0,NaN,NaN,R,R,R,0.416667,0.583333,0.400000,0.600000,-0.166667,-0.200000
3,Arkansas,100.0,71.0,28.0,1.0,NaN,35,27.0,8.0,NaN,NaN,D,D,D,0.710000,0.280000,0.771429,0.228571,0.430000,0.542857
4,California,80.0,49.0,29.0,1.0,1.0,40,25.0,14.0,NaN,1.0,D,R,S,0.612500,0.362500,0.625000,0.350000,0.250000,0.275000

In [9]:
pol2010 = pol2010[["State", "House Leaning", "Senate Leaning"]]
pol2010["Average Leaning"] = (pol2010["House Leaning"] + pol2010["Senate Leaning"]) / 2

In [10]:
pol2010['State'] = pol2010['State'].replace(value_mapping) # Changing state names to abbreviations
pol2010['LocYear'] = pol2010['State'].astype(str) + '2010'
pol2010 = pol2010.drop(columns=["State"])

In [11]:
pol2010.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0       0.142857        0.200000         0.171429  AL2010
1      -0.100000        0.000000        -0.050000  AK2010
2      -0.166667       -0.200000        -0.183333  AZ2010
3       0.430000        0.542857         0.486429  AR2010
4       0.250000        0.275000         0.262500  CA2010

In [12]:
# function to streamline the process

def pol_cleaning(df, state):
    df["House Dem Rate"] = df["House Dem"] / df["Total House"]
    df["House Rep Rate"] = df["House Rep"] / df["Total House"]
    df["Senate Dem Rate"] = df["Senate Dem"] / df["Total Senate"]
    df["Senate Rep Rate"] = df["Senate Rep"] / df["Total Senate"]

    df["House Leaning"] = df["House Dem Rate"] - df["House Rep Rate"]
    df["Senate Leaning"] = df["Senate Dem Rate"] - df["Senate Rep Rate"]

    df = df[["State", "House Leaning", "Senate Leaning"]]
    df["Average Leaning"] = (df["House Leaning"] + df["Senate Leaning"]) / 2

    df['State'] = df['State'].replace(value_mapping) # Changing state names to abbreviations
    df['LocYear'] = df['State'].astype(str) + state
    df = df.drop(columns=["State"])

    return df

### 2011
- The data from 2011 can be found through this link: [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)

In [13]:
pol2011 = pd.read_csv("../data/political/2011.csv")
pol2011.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control
0,Alabama,105.0,39.0,66.0,NaN,NaN,35,12.0,22.0,1.0,NaN,R,R,R
1,Alaska,40.0,16.0,24.0,NaN,NaN,20,10.0,10.0,NaN,NaN,S,R,S
2,Arizona,60.0,20.0,40.0,NaN,NaN,30,9.0,21.0,NaN,NaN,R,R,R
3,Arkansas,100.0,55.0,44.0,NaN,1.0,35,20.0,15.0,NaN,NaN,D,D,D
4,California,80.0,52.0,28.0,NaN,NaN,40,25.0,15.0,NaN,NaN,D,D,D

In [14]:
pol2011 = pol_cleaning(pol2011, state='2011')

In [15]:
pol2011.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0      -0.257143       -0.285714        -0.271429  AL2011
1      -0.200000        0.000000        -0.100000  AK2011
2      -0.333333       -0.400000        -0.366667  AZ2011
3       0.110000        0.142857         0.126429  AR2011
4       0.300000        0.250000         0.275000  CA2011

### 2012
- The data from this section was found from [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)

In [16]:
pol2012 = pd.read_csv("../data/political/2012.csv")
pol2012.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control
0,Alabama,105.0,40.0,65.0,NaN,NaN,35,12.0,22.0,1.0,NaN,R,R,R
1,Alaska,40.0,18.0,22.0,NaN,NaN,20,10.0,10.0,NaN,NaN,S,R,S
2,Arizona,60.0,20.0,40.0,NaN,NaN,30,9.0,21.0,NaN,NaN,R,R,R
3,Arkansas,100.0,55.0,45.0,NaN,NaN,35,20.0,15.0,NaN,NaN,D,D,D
4,California,80.0,52.0,28.0,NaN,NaN,40,25.0,15.0,NaN,NaN,D,D,D

In [17]:
pol2012 = pol_cleaning(pol2012, state='2012')
pol2012.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0      -0.238095       -0.285714        -0.261905  AL2012
1      -0.100000        0.000000        -0.050000  AK2012
2      -0.333333       -0.400000        -0.366667  AZ2012
3       0.100000        0.142857         0.121429  AR2012
4       0.300000        0.250000         0.275000  CA2012

### 2013
- The data from this section was found from [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)

In [18]:
pol2013 = pd.read_csv("../data/political/2013.csv")
pol2013.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control
0,Alabama,105.0,39.0,64.0,NaN,2.0,35,11.0,23.0,1.0,NaN,R,R,R
1,Alaska,40.0,15.0,25.0,NaN,NaN,20,7.0,13.0,NaN,NaN,R,R,R
2,Arizona,60.0,24.0,36.0,NaN,NaN,30,13.0,17.0,NaN,NaN,R,R,R
3,Arkansas,100.0,48.0,51.0,1.0,NaN,35,14.0,21.0,NaN,NaN,R,D,S
4,California,80.0,54.0,26.0,NaN,NaN,40,26.0,12.0,NaN,2.0,D,D,D

In [19]:
pol2013 = pol_cleaning(pol2013, state='2013')
pol2013.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0      -0.238095       -0.342857        -0.290476  AL2013
1      -0.250000       -0.300000        -0.275000  AK2013
2      -0.200000       -0.133333        -0.166667  AZ2013
3      -0.030000       -0.200000        -0.115000  AR2013
4       0.350000        0.350000         0.350000  CA2013

### 2014
- The data from this section was found from [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)

In [20]:
pol2014 = pd.read_csv("../data/political/2014.csv")
pol2014.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control
0,Alabama,105.0,37.0,63.0,1.0,4.0,35,11.0,23.0,1.0,NaN,R,R,R
1,Alaska,40.0,13.0,26.0,NaN,1.0,20,7.0,13.0,NaN,NaN,R,R,R
2,Arizona,60.0,24.0,36.0,NaN,NaN,30,12.0,17.0,NaN,1.0,R,R,R
3,Arkansas,100.0,48.0,51.0,1.0,NaN,35,13.0,22.0,NaN,NaN,R,D,S
4,California,80.0,55.0,25.0,NaN,NaN,40,28.0,11.0,NaN,1.0,D,D,D

In [21]:
pol2014 = pol_cleaning(pol2014, state='2014')
pol2014.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0      -0.247619       -0.342857        -0.295238  AL2014
1      -0.325000       -0.300000        -0.312500  AK2014
2      -0.200000       -0.166667        -0.183333  AZ2014
3      -0.030000       -0.257143        -0.143571  AR2014
4       0.375000        0.425000         0.400000  CA2014

### 2015
- The data from this section was found from [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)

In [22]:
pol2015 = pd.read_csv("../data/political/2015.csv")
pol2015.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control
0,Alabama,105.0,33.0,72.0,NaN,NaN,35,8.0,26.0,1.0,NaN,R,R,R
1,Alaska,40.0,16.0,23.0,1.0,NaN,20,6.0,14.0,NaN,NaN,R,I,S
2,Arizona,60.0,24.0,36.0,NaN,NaN,30,13.0,17.0,NaN,NaN,R,R,R
3,Arkansas,100.0,36.0,64.0,NaN,NaN,35,11.0,24.0,NaN,NaN,R,R,R
4,California,80.0,52.0,28.0,NaN,NaN,40,25.0,12.0,NaN,3.0,D,D,D

In [23]:
pol2015 = pol_cleaning(pol2015, state='2015')
pol2015.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0      -0.371429       -0.514286        -0.442857  AL2015
1      -0.175000       -0.400000        -0.287500  AK2015
2      -0.200000       -0.133333        -0.166667  AZ2015
3      -0.280000       -0.371429        -0.325714  AR2015
4       0.300000        0.325000         0.312500  CA2015

### 2016
- The data from this section was found from [State Partisan Composition Database](https://app.powerbi.com/view?r=eyJrIjoiZWQ5NDAwYzMtOWMwNC00ZDBkLTg3YzgtYjQxMGIxMDFmN2E4IiwidCI6IjM4MmZiOGIwLTRkYzMtNDEwNy04MGJkLTM1OTViMjQzMmZhZSIsImMiOjZ9)

In [24]:
pol2016 = pd.read_csv("../data/political/2016.csv")
pol2016.head()

,State,Total House,House Dem,House Rep,House Third Party,House Vacancies,Total Senate,Senate Dem,Senate Rep,Senate Third Party,Senate Vacancies,Legislative Control,Governor Party,State Control
0,Alabama,105.0,33.0,72.0,NaN,NaN,35,8.0,26.0,1.0,NaN,R,R,R
1,Alaska,40.0,16.0,23.0,1.0,NaN,20,6.0,14.0,NaN,NaN,R,I,S
2,Arizona,60.0,24.0,36.0,NaN,NaN,30,13.0,17.0,NaN,NaN,R,R,R
3,Arkansas,100.0,36.0,64.0,NaN,NaN,35,11.0,24.0,NaN,NaN,R,R,R
4,California,80.0,52.0,28.0,NaN,NaN,40,25.0,14.0,NaN,1.0,D,D,D

In [25]:
pol2016 = pol_cleaning(pol2016, state='2016')
pol2016.head()

   House Leaning  Senate Leaning  Average Leaning LocYear
0      -0.371429       -0.514286        -0.442857  AL2016
1      -0.175000       -0.400000        -0.287500  AK2016
2      -0.200000       -0.133333        -0.166667  AZ2016
3      -0.280000       -0.371429        -0.325714  AR2016
4       0.300000        0.275000         0.287500  CA2016

## Combining Data

In [32]:
pol_df = pd.concat([pol2010, pol2011, pol2012, pol2013, pol2014, pol2015, pol2016], ignore_index=True)

In [33]:
pol_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   House Leaning    343 non-null    float64
 1   Senate Leaning   343 non-null    float64
 2   Average Leaning  343 non-null    float64
 3   LocYear          350 non-null    str
dtypes: float64(3), str(1)
memory usage: 13.1 KB

should i just drop the missing values..?

In [35]:
pol_df[pol_df.isnull().any(axis=1)]

     House Leaning  Senate Leaning  Average Leaning LocYear
26             NaN             NaN              NaN  NE2010
76             NaN             NaN              NaN  NE2011
126            NaN             NaN              NaN  NE2012
176            NaN             NaN              NaN  NE2013
226            NaN             NaN              NaN  NE2014
276            NaN             NaN              NaN  NE2015
326            NaN             NaN              NaN  NE2016

okay since it is all Nebraska I think I am just going to drop it